/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MatchesMatchIdScoreRouteImport } from './routes/matches.$matchId.score'
import { Route as MatchesMatchIdScorecardRouteImport } from './routes/matches.$matchId.scorecard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesMatchIdScoreRoute = MatchesMatchIdScoreRouteImport.update({
  id: '/matches/$matchId/score',
  path: '/matches/$matchId/score',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesMatchIdScorecardRoute = MatchesMatchIdScorecardRouteImport.update({
  id: '/matches/$matchId/scorecard',
  path: '/matches/$matchId/scorecard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/matches/$matchId/score': typeof MatchesMatchIdScoreRoute
  '/matches/$matchId/scorecard': typeof MatchesMatchIdScorecardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/matches/$matchId/score': typeof MatchesMatchIdScoreRoute
  '/matches/$matchId/scorecard': typeof MatchesMatchIdScorecardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/matches/$matchId/score': typeof MatchesMatchIdScoreRoute
  '/matches/$matchId/scorecard': typeof MatchesMatchIdScorecardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/matches/$matchId/score' | '/matches/$matchId/scorecard'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/matches/$matchId/score' | '/matches/$matchId/scorecard'
  id:
    '__root__' | '/' | '/matches/$matchId/score' | '/matches/$matchId/scorecard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MatchesMatchIdScoreRoute: typeof MatchesMatchIdScoreRoute
  MatchesMatchIdScorecardRoute: typeof MatchesMatchIdScorecardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$matchId/score': {
      id: '/matches/$matchId/score'
      path: '/matches/$matchId/score'
      fullPath: '/matches/$matchId/score'
      preLoaderRoute: typeof MatchesMatchIdScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$matchId/scorecard': {
      id: '/matches/$matchId/scorecard'
      path: '/matches/$matchId/scorecard'
      fullPath: '/matches/$matchId/scorecard'
      preLoaderRoute: typeof MatchesMatchIdScorecardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MatchesMatchIdScoreRoute: MatchesMatchIdScoreRoute,
  MatchesMatchIdScorecardRoute: MatchesMatchIdScorecardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
